import {
  FaLaptop,
  FaMobileAlt,
  FaTv,
  FaCamera,
  FaHeadphones,
  FaGamepad,
  FaKeyboard,
  FaPlug,
  FaBatteryFull,
  FaWifi,
  FaPrint,
  FaClock,
  FaTshirt,
  FaShoePrints,
  FaGlasses,
  FaGem,
  FaRing,
  FaShoppingBag,
  FaCut,
  FaHome,
  FaCouch,
  FaBed,
  FaBath,
  FaLightbulb,
  FaUtensils,
  FaCoffee,
  FaAppleAlt,
  FaCarrot,
  FaPizzaSlice,
  FaShoppingBasket,
  FaSpa,
  FaSprayCan,
  FaHeartbeat,
  FaPills,
  FaMedkit,
  FaSmile,
  FaDumbbell,
  FaFutbol,
  FaBicycle,
  FaRunning,
  FaSwimmer,
  FaHiking,
  FaCampground,
  FaTrophy,
  FaBook,
  FaBookOpen,
  FaPencilAlt,
  FaBriefcase,
  FaSuitcase,
  FaMusic,
  FaGuitar,
  FaFilm,
  FaPalette,
  FaPaintBrush,
  FaPuzzlePiece,
  FaChess,
  FaBaby,
  FaPaw,
  FaDog,
  FaCat,
  FaFish,
  FaCar,
  FaTools,
  FaHammer,
  FaWrench,
  FaLeaf,
  FaSeedling,
  FaGift,
  FaTicketAlt,
  FaStore,
} from "react-icons/fa";

export const PRODUCTS_PAGE_LIMIT = 12;

export const CURRENCY = "EGP";

export const DEFAULT_CATEGORY_LABEL = "General";

export const PRODUCT_MESSAGES = {
  ADDED_TO_CART: "Added to cart successfully!",
  ADD_TO_CART_ERROR: "Failed to add to cart. Please check your login status.",
  ADDED_TO_WISHLIST: "Added to wishlist.",
  REMOVED_FROM_WISHLIST: "Removed from wishlist.",
  WISHLIST_ERROR: "Please login first to manage your wishlist.",
  FETCH_ERROR: "Failed to load products. Please try again.",
};

export const PRODUCTS_SORT_OPTIONS = [
  { value: "", label: "Default" },
  { value: "price_asc", label: "Price: Low to High" },
  { value: "price_desc", label: "Price: High to Low" },
  { value: "rating", label: "Top Rated" },
];

export const CATEGORY_ICONS = {
  // Tech
  electronics: FaLaptop,
  computers: FaLaptop,
  laptops: FaLaptop,
  phones: FaMobileAlt,
  mobiles: FaMobileAlt,
  smartphones: FaMobileAlt,
  tv: FaTv,
  cameras: FaCamera,
  photography: FaCamera,
  audio: FaHeadphones,
  headphones: FaHeadphones,
  accessories: FaHeadphones,
  gaming: FaGamepad,
  games: FaGamepad,
  keyboards: FaKeyboard,
  chargers: FaPlug,
  batteries: FaBatteryFull,
  networking: FaWifi,
  printers: FaPrint,
  watches: FaClock,
  wearables: FaClock,

  // Fashion
  fashion: FaTshirt,
  clothing: FaTshirt,
  clothes: FaTshirt,
  apparel: FaTshirt,
  men: FaTshirt,
  women: FaTshirt,
  shoes: FaShoePrints,
  footwear: FaShoePrints,
  eyewear: FaGlasses,
  sunglasses: FaGlasses,
  jewelry: FaGem,
  jewellery: FaRing,
  bags: FaShoppingBag,
  luggage: FaSuitcase,
  tailoring: FaCut,

  // Home
  home: FaHome,
  furniture: FaCouch,
  bedroom: FaBed,
  bathroom: FaBath,
  lighting: FaLightbulb,
  kitchen: FaUtensils,
  appliances: FaPlug,
  garden: FaSeedling,
  outdoor: FaLeaf,
  tools: FaTools,
  hardware: FaHammer,
  diy: FaWrench,

  // Food
  food: FaPizzaSlice,
  groceries: FaShoppingBasket,
  grocery: FaShoppingBasket,
  beverages: FaCoffee,
  drinks: FaCoffee,
  coffee: FaCoffee,
  fruits: FaAppleAlt,
  vegetables: FaCarrot,

  // Beauty & health
  beauty: FaSmile,
  cosmetics: FaSmile,
  makeup: FaPaintBrush,
  skincare: FaSpa,
  fragrance: FaSprayCan,
  perfume: FaSprayCan,
  health: FaHeartbeat,
  pharmacy: FaPills,
  "first-aid": FaMedkit,

  // Sports & outdoors
  sports: FaFutbol,
  fitness: FaDumbbell,
  gym: FaDumbbell,
  cycling: FaBicycle,
  running: FaRunning,
  swimming: FaSwimmer,
  hiking: FaHiking,
  camping: FaCampground,
  trophies: FaTrophy,

  // Media & hobbies
  books: FaBook,
  education: FaBookOpen,
  stationery: FaPencilAlt,
  office: FaBriefcase,
  music: FaMusic,
  instruments: FaGuitar,
  movies: FaFilm,
  art: FaPalette,
  crafts: FaPaintBrush,
  toys: FaPuzzlePiece,
  puzzles: FaPuzzlePiece,
  "board-games": FaChess,

  // Kids & pets
  baby: FaBaby,
  kids: FaBaby,
  pets: FaPaw,
  dogs: FaDog,
  cats: FaCat,
  aquarium: FaFish,

  // Misc
  automotive: FaCar,
  cars: FaCar,
  gifts: FaGift,
  tickets: FaTicketAlt,
  other: FaStore,
  misc: FaStore,
};
